### ISSUE TITLE
Document development

### ISSUE THREAD

**Issue by CoPokBl** [CoPokBl/LongdAI#11]

**Comment by JovDaBoss** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:////Users/jovanmilenkovic/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">

<link rel=themeData
href="file:////Users/jovanmilenkovic/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:////Users/jovanmilenkovic/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-AU style='tab-interval:36.0pt;word-wrap:break-word'>




What Was Tested | How It Was Tested | Expected Result | Actual Result | How It Was Fixed If   Relevant
-- | -- | -- | -- | --
See If The Ai Can Respond To Comments Of All Sorts In   English | Use Filler Words, Bad Vocabulary, Awkward Questions And   Bad Spelling | The Ai Will Respond Correctly To Awkward Questions, Punctuation/   Vocabulary errors And Bad Spelling |   |  
If Someone Of No Knowledge Can Use Our App | Give Someone With No Knowledge Of The App A Try And See If   They Can understand What’s Happening | They Will Be Able To Use The App Completely Fine With No   Prior Knowledge Of The App. | They were able to use the app | N/A 
Appropriate answers According To The Personality Traits   Selected | Ask The Same Question To The Ai To Ensure A Different response   When Different Personalities Are Active | The Ai Will Respond Differently Each Time A Different Personality   Is Active. |   |  
Appropriate Response Time | Ask The AI Long And Short Questions | Have A Response Time of 0 to 5 Seconds |   |  
Test Win Screen And All Functions (Kicks out of App/sends   back to App) | Click On The “Play Life” Button And Click On The “Continue   Chat” Button | The App Kicks You Out When Clicked On “Play Life” Or Continues   The App When Clicked “Continue Chat” |   |  
Test All Boundaries In Regard To Buttons | Click In And Around All Clickable Buttons | The Button Will Only Work When It Is Clicked Inside Its Boundaries |   |  
Test Ticked Circles (only 1 can be ticked) | Click Multiple Tick Able Circles | Only One Box Will Be Able To Be Selected At A Time |   |  
Readability | Give Someone with Glasses, Partial Vision Or Normal Vision   A Go At Reading The Text On Our App | People Will Be Able To Read The Text Even If They Have   Glasses, Partial Vision Or Normal Vision |   |  
See If Saying The Key Word “I Have Friends” Sends You To   The Win Screen | Type “I Have Friends” | Upon Typing “I Have Friends” It Will Send You To A Win   Screen |   |  




</body>

</html>

**Comment by CoPokBl** [comment]
I included extensive internal documentation in the form of dotnet <summary> tags throughout all .cs files

**Comment by CoPokBl** [comment]
done
