### ISSUE TITLE
Evaluate Solution

### ISSUE THREAD

**Issue by CoPokBl** [CoPokBl/LongdAI#13]

**Comment by JovDaBoss** [comment]
### _**Usability**_
The user was easily able to navigate their way through the solution and use the solution. While everything was of ease to use one thing that was confusing users was that when clicking on changing the character the solution wouldn't give a response that it was changed so users just kept on clicking thinking it wasn't working. Other than this small problem the user could understand everything else as it was self explanatory.

### **_Relevance_**
The relevance of our solution was very good as when the user was asking questions its output was always relevant to the question the user asked, although sometimes the bot's json responses weren't processing correctly resulting in a half answer or no answer. The relevance of all of the user options were also really good as the user was able to change characters and personalities to their benefit which was helping the user be more interactive/open to talk with it.
