### ISSUE TITLE
Key Legislation

### ISSUE THREAD

**Issue by JovDaBoss** [CoPokBl/LongdAI#5]

**Comment by JovDaBoss** [comment]
Goals:



![Image](https://github.com/CoPokBl/LongdAI/assets/140989837/6b8d000f-13db-4996-b6c2-89c1a4ee9a65)

**Comment by JovDaBoss** [comment]
/Potential Legal Issues:

- **Privacy Act 1988**
This will not be a big problem for us as the AI bot we will use will receive all the responses as it is a separate party. The group ourselves will not receive any type of data or private data so we will need to make a terms and conditions explaining how the responses you give to the AI will go to Open AI. Open Ai complies with all APP's ranging from 1-13 which means we will be able to use their website for the creation of our Long dAI, and people will be able to use our product safely without any danger caused to them.

The Australian Privacy Principles (APPs) are outlined in the Australian Privacy Act of 1988. The 13 APP's are:

1. APP 1: Open and Transparent Management of Personal Information - This principle refers to managing personal information in an open and transparent way.

2. APP 2: Anonymity and Pseudonymity - Individuals have the option of not identifying themselves or of using a pseudonym when dealing with an APP entity in certain circumstances.

3. APP 3: Collection of Solicited Personal Information - It deals with collecting only necessary personal information and doing so lawfully and fairly.

4. APP 4: Dealing with Unsolicited Personal Information - It concerns how to deal with personal information that is received, but not requested.

5. APP 5: Notification of the Collection of Personal Information - This principle refers to making individuals aware that their personal information is being collected.

6. APP 6: Use or Disclosure of Personal Information - It stipulates that personal information should not be used or disclosed for a purpose other than what is was collected for, except in certain circumstances.

7. APP 7: Direct Marketing - Unauthorised direct marketing is restricted.

8. APP 8: Cross-border Disclosure of Personal Information - It sets out steps to protect personal information before it is disclosed overseas.

9. APP 9: Adoption, Use, or Disclosure of Government Related Identifiers - It's about the adoption of government-related identifiers by certain private sector organisations.

10. APP 10: Quality of Personal Information - It's aiming to ensure the entity holds accurate, up-to-date, and complete personal information.

11. APP 11: Security of Personal Information - It outlines measures to protect the personal information from misuse, loss, unauthorised access, modification, or disclosure.

12. APP 12: Access to Personal Information - Individuals have a right to access their personal information, subject to some exceptions.

13. APP 13: Correction of Personal Information - The principle that guides the updating or correction of personal information to ensure it is accurate and current.

**Comment by CoPokBl** [comment]
[OpenAI privacy policy.txt](https://github.com/CoPokBl/LongdAI/files/12234705/OpenAI.privacy.policy.txt)

**Comment by CoPokBl** [comment]
The provided privacy policy appears to align with several aspects of the Australian Privacy Principles (APPs), but there is little information specifically regarding adherence to all 13 standards. Here's how it might align with some of them:

1. APP 1 - Open and Transparent Management of Personal Information: The policy outlines the types of personal information it collects, how it's used, and when and to whom it might be disclosed.

2. APP 2 - Anonymity and Pseudonymity: The policy does not clearly indicate whether individuals have the option of not identifying themselves or using pseudonyms.

3. APP 3 and APP 4 - Collection of Solicited Personal Information and Unsolicited Personal Information: The policy explains the kinds of personal information the company collects but does not detail how they deal with unsolicited personal information.

4. APP 5 - Notification of the Collection of Personal Information: The policy communicates that it collects data from user interactions, but it does not provide information about notifying users at the point of collection.

5. APP 6 - Use or Disclosure of Personal Information: The policy states that information may be provided to third parties in certain circumstances.

6. APP 11 - Security of Personal Information: The policy outlines some security measures and mentions that it retains personal information for as long as necessary to provide services or for other legitimate business purposes.

The policy doesn't clearly indicate compliance with the other APPs, including direct marketing practices, cross-border disclosure of information, proper handling of government-related identifiers, quality of personal information, accessibility, and correction of personal information. In compliance with all APPs, it's recommended to get a professional opinion if insuring full compliance is a concern.

**Comment by CoPokBl** [comment]
The Australian Privacy Principles (APPs) are outlined in the Australian Privacy Act of 1988. There are 13 APPs in total:

1. APP 1: Open and Transparent Management of Personal Information - This principle refers to managing personal information in an open and transparent way.

2. APP 2: Anonymity and Pseudonymity - Individuals have the option of not identifying themselves or of using a pseudonym when dealing with an APP entity in certain circumstances.

3. APP 3: Collection of Solicited Personal Information - It deals with collecting only necessary personal information and doing so lawfully and fairly.

4. APP 4: Dealing with Unsolicited Personal Information - It concerns how to deal with personal information that is received, but not requested.

5. APP 5: Notification of the Collection of Personal Information - This principle refers to making individuals aware that their personal information is being collected.

6. APP 6: Use or Disclosure of Personal Information - It stipulates that personal information should not be used or disclosed for a purpose other than what is was collected for, except in certain circumstances.

7. APP 7: Direct Marketing - Unauthorized direct marketing is restricted.

8. APP 8: Cross-border Disclosure of Personal Information - It sets out steps to protect personal information before it is disclosed overseas.

9. APP 9: Adoption, Use, or Disclosure of Government Related Identifiers - It's about the adoption of government-related identifiers by certain private sector organizations.

10. APP 10: Quality of Personal Information - It's aiming to ensure the entity holds accurate, up-to-date, and complete personal information.

11. APP 11: Security of Personal Information - It outlines measures to protect the personal information from misuse, loss, unauthorized access, modification, or disclosure.

12. APP 12: Access to Personal Information - Individuals have a right to access their personal information, subject to some exceptions.

13. APP 13: Correction of Personal Information - The principle that guides the updating or correction of personal information to ensure it is accurate and current.

**Comment by JovDaBoss** [comment]
**Privacy and Data Protection Act 2014**
This will not be a big problem for us as the AI bot we will use will receive all the responses as it is a separate party. The group ourselves will not receive any type of data or private data so we will need to make a terms and conditions explaining how the responses you give to the AI will go to Open AI. Open Ai complies with all IPP's ranging from 1-10 which means we will be able to use their website for the creation of our Long dAI, and people will be able to use our product safely without any danger caused to them. We are a victorian company so we will need to follow these as if we don't we will fail to comply and our company could fall.


[IPP 1 – COLLECTION] - The only data that Open Ai collects is critical data for its functions and only for lawful means.
[IPP 2 – USE AND DISCLOSURE] - It Only uses information for the primary purpose it was intended for.
[IPP 3 – DATA QUALITY] - All private data that it does store will be up to date as there is always an option to update it
[IPP 4 – DATA SECURITY] - Open Ai has a strong data security meaning it will be hard for people to hack and take data.
[IPP 5 – OPENNESS] - Open Ai have a terms and conditions and privacy policy with a clearly expressed policy.
[IPP 6 – ACCESS AND CORRECTION] - Individuals are able to see their personal information on open ai.
[IPP 7 – UNIQUE IDENTIFIERS] - we will use unique identifiers to protect the identification of the individual
[IPP 8 – ANONYMITY] - you are able to not be identified 
[IPP 9 – TRANSBORDER DATA FLOWS] - yes the privacy protection policy would follow the traveling person.
[IPP 10 – SENSITIVE INFORMATION] - they do collect sensitive information but will not use it unless allowed to under Certain  circumstances.

**Comment by JovDaBoss** [comment]
**Health Records Act 2001**
we don't store any Health records as our Long dAI will not ask for any health issues. If there was to be an input of any Type of health i just wont be stored and saved.

**Comment by JovDaBoss** [comment]
**Copy Right Act 1968**
We will be following the copy right act 1968 as we are making everything from scratch which would mean we would have copy right over our work. Open AI offers the AI so we would still be following the copy right act even when using their bot for our soloution.

**Comment by JovDaBoss** [comment]
**Ethical Issues**
The Bot has gone under immense testing making sure that it wont say anything outrageous or racist, etc. The bot will never say anything bad unless pushed, manipulated, Forced (etc.) by the user to say it. We have taken all precautions possible to make sure the bot will reduce the chance to say anything bad but of course if the user does push it or manipulate it there is a possibility that the AI will say something Untasteful.  

it might seem unethical for the person as he will need to know that he is talking to a AI bot and not a human. We will need to inform the user before he uses our solution that he will be talking to an AI.
