### ISSUE TITLE
Investigating Problem

### ISSUE THREAD

**Issue by JovDaBoss** [CoPokBl/LongdAI#6]
The AI would have limited emotional intelligence, meaning that it could limit it's ability to provide proper support to people who need help, especially with people who have complex mental health.
The AI could produce biased data results.
The AI may collect and store the user's data which can raise a privacy concern.
There are limitations to creating the AI bot, such as time, skill, and money.
The AI would have ethical considerations such as the bot making harmful comments.
You can solve this problem by enabling filter words for the AI bot. This can be achieved by the AI not being able to use any words that can be sensitive to the user. We would also need cybersecurity to help against anyone who is trying to do phishing or scamming. The AI can not not be biased towards or with the user. 
Information sourced and paraphrased from: https://www.digitaltrends.com/computing/investigation-exposes-murkier-side-of-ai-chatbot-industry/
How we can prevent the AI to be dangerous: https://www.unite.ai/the-dangers-of-ai-chatbots-and-how-to-counter-them/

**Comment by CoPokBl** [comment]
yay
